

services:
  web:
    build: .
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_DB: credit_db
      POSTGRES_USER: rohan
      POSTGRES_PASSWORD: rohan123
    ports:
      - "5432:5432"
      
  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", ""]
    ports:
      - "6379:6379"


  celery:
    build: .
    command: celery -A credit_system worker --loglevel=info

    volumes:
      - .:/app
    depends_on:
      - web
      - redis
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/backend

